# Preface {-}

This is the website for my thesis for doctoral degree in Medical Science at [Karolinska Institutet](https://ki.se), Stockholm (Sweden). The code for reproducing the pdf of my thesis is available as a public repository on [GitHub](https://github.com/alecri/kappa). The website is a direct translation of the pdf in a web page, written using the [thesisdown]( https://github.com/ismayc/thesisdown) template in [bookdown]( https://github.com/rstudio/bookdown). 


----------------

> The function of the expert reviewer is not to be more right than other people, but to be wrong for more sophisticated reasons

-- Iain Chalmers and Douglas G. Altman  
_Systematic Reviews_, 1995

----------------

## Abstract {-}

Dose--response meta-analysis is a statistical procedure for combining and contrasting the evidence on the association between a continuous exposure and the risk of a health outcome. Different papers refined selected aspects of the methodology, such as implementation of flexible strategies and extensions to multivariate meta-analysis. However, there were still several relevant questions that needed to be addressed. This thesis aims to address these issues by developing and implementing new strategies and ad-hoc measures (paper I), including tools for evaluating the goodness-of-fit (paper II), a new measure for quantifying the impact of heterogeneity (paper III), a strategy to deal with differences in the exposure range across studies (paper IV), and a one-stage approach to estimate complex models without excluding relevant studies (paper V).

In paper I, we described the implementation of the main aspects of the methodology in the **dosresmeta** R package available on CRAN. Dedicated functions were written to facilitate specific tasks such as definition of the design matrix and prediction of the pooled results. We illustrated how to estimate both linear and non-linear curves, conduct test of hypotheses, and present the results in a tabular and graphical format reanalyzing published aggregated dose--response data.

In paper II, we discussed how to evaluate the goodness-of-fit. The proposed solutions consist of descriptive measures to summarize the agreement between fitted and observed data (the deviance and the coefficient of determination), and graphical tools to visualize the fit of the model (decorrelated residuals-versus-exposure plot). A reanalysis of two published meta-analyses exemplified how these tools can improve the practice of quantitative synthesis of aggregated dose--response data. 

In paper III, we proposed and characterized a new measure, $\hat R_b$, to quantify the proportion of the variance of the pooled estimate attributable to the between-study heterogeneity. Contrary to the available measures of heterogeneity, $\hat R_b$ does not make any assumption about the distribution of the within-study error variances, nor does it require specification of a typical value for these quantities. The performance of the proposed measure was evaluated in an extensive simulation study. We demonstrated how to present and interpret the $\hat R_b$ re-analyzing three published meta-analyses.

In paper IV, we extended a point-wise approach to dose--response meta-analysis of aggregated data. The strategy consists of combining predicted relative risks for a fine grid of exposure values based on potentially different dose--response models. A point-wise approach can improve the flexibility in modeling the study-specific curves and may limit the impact of extrapolation by predicting the study-specific relative risks based on the observe exposure range. We illustrated the methodology using both individual and aggregated participant data.

In paper V, we formalized a one-stage approach for dose--response meta-analysis in terms of a linear mixed model. We explained the main aspects of the methodology and how to address the same questions frequently answered in a two-stage analysis. Using both hypothetical and real data, we showed how the one-stage approach can facilitate the assessment of heterogeneity over the exposure range, model comparison, and prediction of individual dose--response associations. The main advantage is that flexible curves can be estimated regardless of the number of data-points in the individual analyses.

In conclusion, the methods presented in this thesis enrich the set of tools available for applying dose--response meta-analyses and for addressing specific questions including goodness-of-fit evaluation (paper II) and quantification of heterogeneity (paper III). In addition, we presented alternative models for pooling results in case of heterogeneous exposure range (paper IV) and for estimating complex models without excluding relevant studies (paper V). The proposed methods have been illustrated using real data and implemented in user-friendly R packages available on CRAN (paper I).

## List of publications {-}

- Alessio Crippa, and Nicola Orsini  
**Multivariate dose--response meta-analysis: the dosresmeta R Package**  
_Journal of Statistical Software_ 2016; 72(1), 1--15

- Andrea Discacciati, Alessio Crippa, and Nicola Orsini  
**Goodness of fit tools for dose--response meta-analysis of binary outcomes**  
_Research Synthesis Methods_ 2017 Jun; 8(2):149.

- Alessio Crippa, Polyna Khudyakov, Molin Wang, Nicola Orsini, and Donna Spiegelman  
**A new measure of between-studies heterogeneity in meta-analysis**  
_Statistics in Medicine_ 2016; 35(21), 3661--75  

- Alessio Crippa, Ilias Thomas, and Nicola Orsini  
**A pointwise approach to dose-response meta-analysis of aggregated data**  
_Manuscript_ 2018

- Alessio Crippa, Andrea Discacciati, Matteo Bottai, Donna Spiegelman, and Nicola Orsini  
**One-stage dose--response meta-analysis for aggregated data**  
_Manuscript_ 2018


## Related publications {-}

- Ehimen C. Aneni, Alessio Crippa, Chukwuemeka U. Osondu, Javier Valero-Elizondo, Adnan Younus, Khurram Nasir, and Emir Veledar  
**Estimates of Mortality Benefit From Ideal Cardiovascular Health Metrics: A Dose Response Meta-Analysis**  
_Journal of the American Heart Associatio_} 2017 Dec 1; 6(12):e006904.

- Alessio Crippa, Susanna C. Larsson, Andrea Discacciati, Alicja Wolk, and Nicola Orsini  
**Red and processed meat consumption and risk of bladder cancer: a dose--response meta-analysis of epidemiological studies**  
_European Journal of Nutrition_ 2016 Dec; 22:1-3.


- Andrea D. Smith, Alessio Crippa, James Woodcock, and Sören Brage  
**Physical activity and incident type 2 diabetes mellitus: a systematic review and dose--response meta-analysis of prospective cohort studies**  
_Diabetologia_ 2016;59(12):2527-45.

- Marco Vinceti, Tommaso Filippini, Alessio Crippa, Agnes de Sesmaisons, Lauren A. Wise, and Nicola Orsini  
**Meta-Analysis of Potassium Intake and the Risk of Stroke**
_Journal of the American Heart Association_ 2016; 5(10), e004210

- Alessio Crippa, and Nicola Orsini  
**Dose--response meta-analysis of differences in means**  
BMC Medical Research Methodology} 2016 Dec, 16(1):91.

- Emir Veledar, Alessio Crippa, Chukwuemeka U. Osondu, Adnan Younus, and Khurram Nasir   
**Letter to Editor: Ideal cardiovascular health metrics and risk of cardiovascular disease or mortality**  
_International Journal of Cardiology_ 2016 Nov 1; 222:737

- Alessio Crippa, Andrea Discacciati, Nicola Orsini, and Viktor Oskarsson  
**Letter: coffee consumption and gallstone disease---a cautionary note on the assignment of exposure values in dose--response meta-analyses**  
_Alimentary Pharmacology & Therapeutics_ 2016; 43(1), 166-167

- Susanna C. Larsson, Alessio Crippa, Nicola Orsini, Alicja Wolk, and Karl Michaelsson  
**Milk consumption and mortality from all causes, cardiovascular disease, and cancer: a systematic review and meta-analysis**  
_Nutrients_ 2016; 7(9), 7749-7763

- Daniela Di Giuseppe, Alessio Crippa, Nicola Orsini, and Alicja Wolk  
**Fish consumption and risk of rheumatoid arthritis: a dose-response meta-analysis**  
_Arthritis Research & Therapy_ 2014; 16(5), 446

- Alessio Crippa, Andrea Discacciati, Susanna C. Larsson, Alicja Wolk, and Nicola Orsini   **Coffee consumption and mortality from all causes, cardiovascular disease, and cancer: a dose--response meta-analysis**  
_American Journal of Epidemiology_ 2014; 180(8), 763-775


## List of abbreviations {-}


| | |
|-------------|------------|
AIC | Akaike Information Criterion |  
BLUP | Best Linear Unbiased Prediction |  
CI | Confidence Intervals  | 
CRAN | Comprehensive R Archive Network |  
CS | Cubic Splines |  
df | Degrees of Freedom  | 
GLS | Generalized Least Squares  | 
GRSS | Generalized Residual Sum of Squares |  
GTSS | Generalized Total Sum of Squares  | 
FP2 | Second-degree Fractional Polynomials |  
ICC | Intraclass Correlation Coefficient |  
IPD | Individual Participant Data  | 
logRR | log--Relative Risk |  
LOWESS | Locally Weighted Scatterplot Smoothing  | 
ML | Maximum Likelihood  | 
RCS | Restricted Cubic Splines |  
REML | Restricted Maximum Likelihood |  
$R^2$ | Coefficient of Determination |  
RR | Relative Risk |  
SEER | Surveillance, Epidemiology, and End Results |  
VPC | Variance Partition Coefficient |  
WLS | Weighted Least Squares |  