# Acknowledgements {-}

I would like to thanks all the many people who directly or indirectly contributed to this thesis for their support and encouragement during these years. 
<br />

First of all, **Nicola Orsini**, my main supervisor. Thanks for giving me the opportunity of undertaking this doctoral studies and for your exceptional guidance. With your genuine and continuous enthusiasm, you pushed me outside my comfort zone and motivated me to do my best. Your advice and quotes have always been  appreciated and will guide me in the important decisions inside and outside the academia. 
<br />

My co-supervisors **Alicja Wolk**, **Donna Spiegelman**, and **Matteo Bottai**. Alicja, you welcomed me in your unit and introduced me to the challenging word of nutritional epidemiology. Thanks for your valuable comments and for forcing me to improve my Swedish. Donna, you gave me the opportunity to visit the Harvard School of Public Health and work under your supervision. We had very nice discussions and I learned a lot from your extensive experience. Thanks Matteo for always taking time to meet me and answer my questions. You helped me to think critically and look at things from a different perspective.

<br />
All the co-authors of the studies for your important contributions and for starting rewarding collaborations. A particular thanks to **Susanna Larsson** for your quick and frequent help, and to **Rino Bellocco** for putting me in contact with Nicola and for involving me in many activities. Meeting you on the train has probably changed my life. A warm thank you to **Rosaria Galanti** for engaging me in different collaborations and for being my personal life coach, especially for medical assistance.
<br />

**Andrea Discacciati** and **Andrea Bellavia**, for the nice and constructive discussions but more importantly for making our daily working life entertaining. Thanks to **Xingwu Zhou**, **Filip Andersson**, and **Fabio Castagna** for their support and aid, in particular during our frequent Ping-Pong games. **Daniela Di~Giuseppe**, for our profitable collaborations and coffee breaks. **Renee Gardner**, for being a wonderful co-teacher and for proofreading this thesis.
<br />

**Viktor Oskarsson** and **Eleonor Säfsten**, with whom I shared office, concerns and laughs, and pleasant extra activities. Thanks for being patient with the too many Italians around you. An extra warm thanks goes to **Carolina Donat Vargas**, **Constance Boissin**, **Emilia Riggi**, **Nada Hana**, and **Paolo Frumento**. All my present and past colleagues at the department of Public Health Sciences: **Antonio Ponce De Leon**, **Ashley Mcallister**, **Asli Kulane**, **Bo Burström**, **Diana Corman**, **Dominika Seblova**, **Erika Saliba Gustafsson**, **Jad Shedrawy**, **Janne Agerholm**, **Malin Pettersson**, **Megan Doheny**, **Melody Almroth**, **Pär Schön**, **Sara Delilovic**, **Sara Fritzell**, **Stefania Manetti** and **Zangin Zeebari**; and the Unit of Nutritional Epidemiology: **Agneta Åkesson**, **Alice Wallin**, **Ann Burgaz**, **Anna Ingemarsdotter**, **Becky Leung**, **Bettina Julin**, **Camilla Olofsson**, **Frej Stilling**, **Holly Harris**, **Iffat Rahman**, **Ilias Thomas**, **Jinjin Zheng Selin**, **Katica Anusic**, **Lollo Sjöholm**, **Mimi Throne-Holst**, **Niclas Håkansson**, **Susanne Rautiainen Lagerström**, **Otto Stackelberg**, and **Thanasis Tektonidis**.
<br />

My parents, **Margherita** and **Pierangelo**, my sister **Gaia**, and my aunt **Alessandra**, for their unconditional love and support. All that I've become, I owe to you.
<br />

Last but not least thanks to all my friends in Italy, Sweden, and around the world. In particular, to my present and past flatmates **Andrea Serio**, **Davide Bossoli**, **Daniela Mariosa**, **Elena Raffetti**, **Lucia Michielon** and
**Marco Trevisan**, thanks for bearing with me.
